### ISSUE TITLE
Bug in progress reporter

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#188] opened 2020-08-23 17:11 UTC
It is only triggered when you enter from the main screen. 

Also, when you enter from the practice, it works, but it defaults to the first item in the list, the default should be the unit you are entering from if possible... In other words, I was using test 3 tdf, and I went to the progress reporter and is showed me test 2 tdf report, and I needed to switch to test 3 report even though I was just practice in test 3 tdf...

**Comment by imrryr** [comment] 2020-08-23 17:11
![Screenshot (18)](https://user-images.githubusercontent.com/13023147/90984315-bae9c300-e539-11ea-995c-fe73f552384d.png)

**Comment by imrryr** [comment] 2020-08-23 17:11
Error only happens if entering from main screen....

**Comment by andrewtackett** [comment] 2020-08-24 18:07
This appears to be a result of you reusing a tdf and renaming it in the database?  It doesn't seem to be a valid error for normal use cases.

**Comment by andrewtackett** [comment] 2020-08-24 18:32
Closing as unable to reproduce.  Please open a new issue if this pops up again.

**Closed by andrewtackett** 2020-08-24 18:32 UTC
