### ISSUE TITLE
Bug in speech recog

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#24] opened 2019-09-08 16:41 UTC
How does the student indicate skip/hit enter to the next item with no response? Can we have special word reserved for skipping trials with voice command?

When I hit enter when I was stuck it marked me incorrect, but the trial did not end and the transcription was still going. So, I used the feedback from hitting incorrect to then correctly answer, at which time it remarked me correct, and continued.... The keyboard should supersede transcription.

Also, what does     speechIgnoreOutOfGrammarResponses>false<speechIgnoreOutOfGrammarResponses do?

**Comment by andrewtackett** [comment] 2019-09-10 19:18
Couldn't reproduce.  Seems like it could be a race condition/timing error.  We'll close this for now and reopen if we can reproduce in the future.

**Closed by andrewtackett** 2019-09-10 19:18 UTC
