### ISSUE TITLE
Tone learning tdf consent form does not load

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#379] opened 2021-11-03 22:38 UTC
**Describe the bug**
froze at content loading during local operation

**To Reproduce**
should happen if you just start it using Meng's tdf locally with the new code that is supposed to give the first unit... It froze before that first unit with all the errors below

**Expected behavior**
Consent form is displayed

**Screenshots**
​
![image (3)](https://user-images.githubusercontent.com/13023147/140212106-806d79c3-3f0d-4865-b133-ed91c1b5d8aa.png)
![image (2)](https://user-images.githubusercontent.com/13023147/140212112-2abde2f2-fc82-4d80-8e18-8b9729e3b477.png)
![image (1)](https://user-images.githubusercontent.com/13023147/140212116-a436815f-42ab-4e26-952f-cf16a4538ddb.png)
![image (4)](https://user-images.githubusercontent.com/13023147/140212120-d38ba175-26d0-4450-8ccf-ab32db942848.png)

**Comment by MegaGeese** [comment] 2021-11-08 14:52
I wasn't able to reproduce this issue. Try to make sure that they are on the latest version of mofacts with `git fetch` and `git pull`

**Comment by imrryr** [comment] 2021-11-08 16:32
I sent this to Meng and cc'd you. Please followup if it doesn't work for her.

**Comment by MegaGeese** [comment] 2021-11-08 17:55
Looks like Meng was able to get it working. Closing this issue now.

**Closed by MegaGeese** 2021-11-08 17:55 UTC
Labels: bug, Highest
