### ISSUE TITLE
error shuffling clusters

### ISSUE THREAD

**Issue by lukeEG** [memphis-iis/mofacts-ies#79] opened 2019-11-11 18:55 UTC
ShuffleClusters appears to be broken:
Previously, <shuffleclusters>0-99</shuffleclusters> in <setspec>, followed by  
<clusterlist>0-19</clusterlist> would provide a random subset of the total possible clusters. 
Currently, it only provides the _first_ 20 (when clusterlist is defined within<learningsession>).
 I don't think this was an issue in September (but that was with <assessmentsession>), so some recent changes may have caused the problem.

**Comment by andrewtackett** [comment] 2019-11-11 21:43
Issue was that learning sessions do not honor shuffle clusters.  Should be implemented with commit: 25cbd281657d0ecb9f7f8130d5b6449ef04a5d8d

**Comment by andrewtackett** [comment] 2019-11-13 20:52
Luke tested and this seems to work as intended.  Closing issue.

**Closed by andrewtackett** 2019-11-13 20:52 UTC
Labels: enhancement
